version: "3"

services:
  api:
    container_name: "go_api"
    build: .
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
      postgres-test:
        condition: service_healthy

  postgres:
    container_name: "go_api_database"
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "golang"
    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 60s
      retries: 10
      start_period: 80s 
  
  postgres-test:
    container_name: "go_api_database_test"
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "test"
    ports:
      - "5434:5432"
    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 60s
      retries: 10
      start_period: 80s 

volumes:
  postgres_data: